--Arbitration insert
INSERT INTO ARBITRATION_TRADE(
	AMOUNT,
	BUY_EXCHANGE,
    SELL_EXCHANGE,
    BUY_PRICE,
	TOTAL_BUY_COST,
	SELL_PRICE,
	TOTAL_SELL_COST,
	PROFIT,
	EXECUTION_DATETIME,
	CREATE_DATETIME
)
values(
	1.123323004,
	'Bitstamp',
	'Kraken',
	1.23,
	12002.11,
	1.20,
	12000.11,
	0.03,
	getDate(),
	getDate()
)

--Arbitration UPDATE
UPDATE
	ARBITRATION_TRADE
SET
	AMOUNT = 1.0,
	BUY_EXCHANGE = 'Kraken',
	SELL_EXCHANGE = 'Bitstamp',
	BUY_PRICE = 2.13,
	TOTAL_BUY_COST = 1.99,
	SELL_PRICE = 2.13,
	TOTAL_SELL_COST = 4.56,
	PROFIT = 109000,
	EXECUTION_DATETIME = '2014-10-27 21:58:20',
	LAST_MODIFIED_DATETIME = '2014-10-27 21:58:20'
WHERE
	ID = 1
	
--Transfer INSERT
INSERT INTO TRANSFER(     
	ORIGIN_EXCHANGE,     
	DESTINATION_EXCHANGE,     
	AMOUNT,     
	INITIATE_DATETIME,     
	COMPLETE_DATETIME,     
	CREATE_DATETIME,     
	LAST_MODIFIED_DATETIME 
) 
OUTPUT INSERTED.ID values(     
	'Bitstamp', 
	'Kraken', 
	1.32324234345345, 
	'2014-11-01 17:08:48', 
	'2014-11-01 18:08:48', 
	'2014-11-01 17:08:48', 
	'2014-11-01 17:08:48'
)

--Arbitration Manager Insert
insert into ARBITRATION_RUN(
	Name,
	USE_ANX,
	USE_BITSTAMP,
	USE_BTCE,
	USE_HITBTC,
	USE_ITBIT,
	USE_JUSTCOIN,
	USE_KRAKEN,
	USE_PAYMIUM,
	MINIMUM_PROFIT_FOR_TRADE,
	SEARCH_INTERVAL,
	MAX_BTC_FOR_TRADE,
	LOG_FILE,
	START_DATETIME,
	END_DATETIME,
	CREATE_DATETIME,
	LAST_MODIFIED_DATETIME)
OUTPUT INSERTED.ID VALUES(
	'Test',
	0,
	0,
	0,
	1,
	1,
	null,
	0,
	1,
	0.03,
	10,
	1.2,
	'somefile/onmycomputer/filename.csv',
	GETDATE(),
	NULL,
	GETDATE(),
	GETDATE()
)

--Arbitration Run update
UPDATE 
	ARBITRATION_RUN
SET
	NAME = 'Test',
	USE_ANX = 0,
	USE_BITSTAMP = 0,
	USE_BTCE = 0,
	USE_HITBTC = 1,
	USE_ITBIT = 1,
	USE_JUSTCOIN = null,
	USE_KRAKEN = 0,
	USE_PAYMIUM = 1,
	MINIMUM_PROFIT_FOR_TRADE = 0.03,
	SEARCH_INTERVAL = 10,
	MAX_BTC_FOR_TRADE = 1.2,
	LOG_FILE = 'somefile/onmycomputer/filename.csv',
	start_datetime = GETDATE(),
	end_datetime = null,
	CREATE_DATETIME = GETDATE(),
	LAST_MODIFIED_DATETIME = GETDATE()
WHERE
	ID = 1
